### PR TITLE
Improve quickstart

### PR DESCRIPTION
**Pull request by 0biWanKenobi**
I've tried to improve grammar and syntax for the QuickStart page. I hope it will make the docs more readable, please comment if you spot any mistakes or have suggestions for improvement. I'll be happy to make amends and improve it further :)

### CODE REVIEW

**Comment by 0biWanKenobi** [comment]
PS I've noticed that part of the markdown docs haven't been published under the 7.x.x version folder. This is why I've made this PR on the latest available folder, which is 6.x.x.  Is that intentional or should we copy the missing ones over from  6.x.x ?

**Comment by nodkz** [comment]
I've just looked at `website/versioned_docs` and `package.json` scripts and remembered that source documents are taken from the main repo https://github.com/graphql-compose/graphql-compose/tree/master/docs 
Your changes may be overwritten if somebody makes changes there.

Could you please make your changes in the main repo?

**Comment by nodkz** [comment]
And your grammar fixes are really really good. The docs become much better 👍

**Comment by 0biWanKenobi** [comment]
> I've just looked at `website/versioned_docs` and `package.json` scripts and remembered that source documents are taken from the main repo https://github.com/graphql-compose/graphql-compose/tree/master/docs
> Your changes may be overwritten if somebody makes changes there.
> 
> Could you please make your changes in the main repo?

Sure thing!

**Comment by 0biWanKenobi** [comment]
Moved PR to main branch [here](https://github.com/graphql-compose/graphql-compose/pull/328)

**Pull request closed without merging**
